### ISSUE TITLE
Error with codeintel and sublinter

### ISSUE THREAD

**Issue by wizsilex** [mgussekloo/Tabright#1]
When i close a file this error appears in ST2 console.
I think it make my sublime crash on startup too.

Traceback (most recent call last):
File "./sublime_plugin.py", line 180, in on_close
File "./sublime_plugin.py", line 154, in run_timed_function
File "./sublime_plugin.py", line 179, in 
TypeError: on_close() takes exactly 1 argument (2 given).

**Comment by mgussekloo** [comment]
Could you check if the latest commit fixes things? Functionality also changed a bit, to be more like how Firefox handles tabs.

**Comment by wizsilex** [comment]
It fixed the error in ST2 console,
but when i quit ST2 with open documents,
and reopen ST2 it crashes.
Apple Crash Description: http://pastebin.com/un9A8ptJ
GDB: http://pastebin.com/GMv1Hwr2

**Comment by mgussekloo** [comment]
I can't reproduce this error... Are you sure this error is related to my plugin?

**Comment by wizsilex** [comment]
When i remove your plugin the problem stops.
So i guess it's related.

**Comment by mgussekloo** [comment]
Hm, it seems as though the plugin tries to "shift right" too many tabs upon reopening and crashes the editor. It should do nothing when Sublimetext is simply reopening files.

I'm not all that fluent in Python, so I'll ask around on the Sublimetext forum.

**Comment by mgussekloo** [comment]
I tried a rather hacky fix. Maybe it works for you? I've asked on the Sublimetext forum for a better solution.

**Comment by wizsilex** [comment]
It seems to be working better now, hasn't crashed ST2 on open/reopen when i have tryed now.
:)

**Comment by mgussekloo** [comment]
I implemented a better solution, explained to me by Bizoo on the forum. Could you test it once more? Thanks for helping me improve the plugin!

**Comment by wizsilex** [comment]
Looks like the latest changes makes it crash again.

**Comment by mgussekloo** [comment]
Thanks for testing, sorry for a disappointing update... 

I can't reproduce the problem now (whereas I could with the old version). Bit of a stretch, but could you try removing your session file? On a Mac, it's a .sublime_session file in the folder ~/Library/Application Support/Sublime Text 2/Settings.
If that doesn't help either, I'll look into a better solution...

**Comment by wizsilex** [comment]
It might have worked to delete the session file. It has not crashed now, I have tried to reproduce it, but looks like good now. I will post if i have more problems with it.
really love the plugin. It makes it easy to open new files, so they don't disappear in all open files.
Thanks for all the help :-) :+1:

**Comment by mgussekloo** [comment]
Thanks!
