### ISSUE TITLE
Crash when closing penultimate tab

### ISSUE THREAD

**Issue by nowotny** [mgussekloo/Tabright#2]
Sublime crashes when closing the penultimate tab. 

For example: if I have 3 tabs, it crashes when closing the middle one.

I tested this and reproduced on clean install on Windows XP and Windows 7.

**Comment by mgussekloo** [comment]
Currently very busy with other projects, but I will look into this as soon as possible.
For now you could try removing everything below (and including) the "def on_close(view):" line in the Python file.

**Comment by mgussekloo** [comment]
A fix has been pushed. Please see if it works for you.
