### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by scarfacedeb** [mgussekloo/Tabright#3]
I installed this plugin using Package Manager, closed the editor and now it's throwing this error when i'm trying to open it.

```
/usr/bin/sublime-text: line 3: 11052 Segmentation fault      /usr/lib/sublime-text-2/sublime_text --class=sublime-text-2 "$@"
```

Error disappeared after I removed the plugin.

Using: Crunchbang Waldorf (Debian sid) x86_64

**Comment by mgussekloo** [comment]
Did the program crash without you even using the tab plugin? That makes it hard to debug... You could try removing your session file, and start with a clean session.

**Comment by mgussekloo** [comment]
Could you try removing your session file? Also, I've updated the plugin today. Hopefully it helps.
