### ISSUE TITLE
I'd like to be able to open tabs on the left

### ISSUE THREAD

**Issue by simonexmachina** [mgussekloo/Tabright#4]
Given that we have "Close tabs to the right", I'd like all new tabs to be opened on the left. I had a go at it, but I have zero Python skills so I couldn't get it to work. Do you have any interest in add this as an option to your plugin?

**Comment by mgussekloo** [comment]
Hi Simon,

Do you mean on the left of the currently active tab, or just on the far left? I'm not that good at Python myself, but I'll give it a try.

**Comment by simonexmachina** [comment]
At the far left. You'd think it'd be simple, but it just keeps crashing for
me. Thanks!

Cheers,

Simon

**Comment by mgussekloo** [comment]
Hi Simon,

I've added a preference option. The default is far_right, but you can change it in your user-preferences to far_left. Let me know if this works for you.

**Comment by simonexmachina** [comment]
Thank you! Works perfectly :)

I'm sure I tried that, have no idea why it wasn't working for me :|

**Comment by simonexmachina** [comment]
However, it doesn't open on the left when I use the "Goto Anything" hotkey.

**Comment by mgussekloo** [comment]
Hmm could you try it again? This is kind of challenging :)

**Comment by simonexmachina** [comment]
Yep, seems to work well. Thank you! I can see that you had to jump through
some hoops to get that working, so thanks :) I'll let you know if I see any
issues.

Cheers,

Simon

**Comment by mgussekloo** [comment]
No problem. Just reopen the ticket :)
