### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [mgussekloo/Tabright#5]
Hi. Thanks for the great plugin but there's an extra feature which would make it even more useful.

A new option to open new tabs at far-right/far-left _only when opening new files from the file system (double-click)_.

Cheers.

**Comment by mgussekloo** [comment]
Hi 0kb,
Thanks for your suggestion. I'm not sure I understand what you need. How would this work? Can you describe the different ways of opening files, and the different behaviors you'd like to see?

**Comment by ghost** [comment]
Well I was wondering if we could have both worlds. If I'm opening a file from Path Finder (OS X File Manager) I want it to open in the last tab. If I'm opening a file from a project or the user settings file, for example, I may want it to open next to the active tab.

Of course, I'm referring to OS X and the following option in the Default settings, which I set to false...

```
// OS X only: When files are opened from Finder, or by dragging onto the
// dock icon, this controls if a new window is created or not.
"open_files_in_new_window": true,
```

So maybe something like...

```
{
"open_new_tabs_at": "far_right",
"only_external": "true"
}
```

also referring to files opened from Finder/Path Finder. But I'm not sure if Windows/Linux users could benefit from this.
