### ISSUE TITLE
Order according the stack

### ISSUE THREAD

**Issue by franciscolourenco** [mgussekloo/Tabright#7]
Hi, would be nice to be have tabs ordered according to stack, so whenever you press ctrl+tab the activated tab is moved to the right.

Tanks

**Comment by mgussekloo** [comment]
Thanks for the suggestion. Actually correctly re-ordering the stack would be a huge improvement, but I'm not sure it's all that easy with the ST2 API. For now, I use cmd+shift+left and cmd+shift+right (on a mac) to navigate through the open tabs, and that usually works with Tabright.
Maybe I'll update the plugin to work with the ST3 API, and hopefully it will be easier to implement something like Tabright.
